### PR TITLE
change module ver

### PR DESCRIPTION
**Pull request by haturatu**
I encountered a permission error with the current deno.json, so I upgraded the version using deno.json

### CODE REVIEW

**Comment by haturatu** [comment]
No problem, here is the translation:

```
"changelog": "deno run --allow-read --allow-write https://deno.land/x/changelog@v2.1.0/bin.ts"
```

**Comment by haturatu** [comment]
I committed changes to copy images from the upload folder during the build process because uploaded images via /admin were not accessible due to incorrect image paths. Are there other solutions?

**Comment by oscarotero** [comment]
Thanks, good catch!
Just one thing: can you move the `copy("uploads")` to plugins.ts file? It could be [after this line](https://github.com/lumeland/theme-simple-blog/blob/main/plugins.ts#L64).

**Comment by oscarotero** [comment]
thank you!

**Comment by haturatu** [comment]
Thank you! it's solved.

Regarding another issue, it seems that the image Markdown format URL copying isn't working on my smartphone and my friend's Firefox browser when accessing:

https://cdn.jsdelivr.net/gh/lumeland/cms@0.5.2/static/components/u-copy.js

If I can resolve it on my own, I'll report it in a separate repository. It works fine on Chromium.

thanks!

**Pull request merged**
