### PR TITLE
update: use sitemap plugin from experimental-plugins

### PR DESCRIPTION
**Pull request by wangbinyq**
Pages that have not date attribute should ignore lastmod.

### CODE REVIEW

**Comment by oscarotero** [comment]
@wangbinyq Thanks for this. `page.data.date` value must exist always, because Lume create it if it's not manually defined. Do you have any example where this value doesn't exist?

**Comment by wangbinyq** [comment]
Any pages except post pages dont have `page.data.date` and is included in sitemap.

Here is the sitemap of the demo:
image

**Comment by oscarotero** [comment]
Mmm, Ok. This seems a bug related with remote files, I'll work on that.
Besides, the 404 page shouldn't be listed here, there must be a `if` to filter it.

I think this is OK as a temporary workaround put at some point the experimental plugin [sitemap](https://github.com/lumeland/experimental-plugins/blob/main/sitemap/sitemap.ts) could be moved to Lume repo.

**Comment by wangbinyq** [comment]
Ok, I like the sitemap plugin.
Also this fix is not needed. Should we close this pr?

**Comment by oscarotero** [comment]
Ok, we can close this PR, or modify it to use the sitemap plugin from the experimental repo:

```ts
import siteMap from "https://raw.githubusercontent.com/lumeland/experimental-plugins/main/sitemap/sitemap.ts";

site.use(siteMap());
```

**Comment by wangbinyq** [comment]
> Could you modify the PR to use the sitemap plugin from the experimental repo?:
> 
> ```ts
> import siteMap from "https://raw.githubusercontent.com/lumeland/experimental-plugins/main/sitemap/sitemap.ts";
> 
> site.use(siteMap());
> ```

Ok, I will try.

**Comment by wangbinyq** [comment]
> Could you modify the PR to use the sitemap plugin from the experimental repo?:
> 
> ```ts
> import siteMap from "https://raw.githubusercontent.com/lumeland/experimental-plugins/main/sitemap/sitemap.ts";
> 
> site.use(siteMap());
> ```

This sitemap still has the same problems for this blog theme, also I find a bug in author page.  

image

**Comment by oscarotero** [comment]
Ok, there are some bugs:
- The remote pages don't have the date value, this is why they have `undefined` in the sitemap. This is a Lume bug that I'll fix in the next version.
- The author issue is related with the `author` key in the `_data.yml` file. Due it's used only for the feeds, I just remove it and now works fine.
- I've updated the sitemap plugin to don't print the `lastmod` value if it doesn't exist: https://github.com/lumeland/experimental-plugins/commit/b75edba434ab80d0b9033233f6ade19c09825eb7.

So the only thing to do is to use plugin to generate the sitemap. This includes:
- Import and use the plugin from the experimental plugins repo.
- Remove the sitemap and robots.txt pages in the src folder, because they aren't needed anymore.
- Remove these files also in the mod.ts files to don't load them remotely.

**Comment by oscarotero** [comment]
Thank you!!

**Pull request merged**
