### PR TITLE
Cutting down the character count in the Postlist and resolving the issue where Mastodon comments display incorrectly on smartphones.

### PR DESCRIPTION
**Pull request by haturatu**
demo

https://soulminingrig.com/

image
`src/index.vto`
i made sure that the articles on the homepage are properly trimmed and displayed neatly when posted.

## before

`PC` Okay...
image

`smartphone` aaaa!!
image

## after
`src/style.css`
```
.comments {
  display: contents;
}
```
`PC`
image

`smartphone` 
image

### CODE REVIEW

**Comment by oscarotero** [comment]
The excerpt value is generated searching for the comment `<!-- more -->` in the post body. See the code here: https://github.com/lumeland/theme-simple-blog/blob/main/plugins.ts#L69-L71

Additionally, you can create a different excerpt in the frontmatter:

```md
---
excerpt: "This is the excerpt"
---

Body o the post
```

The excerpt is intentionally not limited because some people prefer to show the entire post in the homepage, instead of only a small intro.

As an idea, to generate excerpts automatically is modifying the plugin options. For example:

```js
const site = lume();

site.use(blog({
    excerpt: {
      size: 100
    }
}));
```

And this option can be used [in the excerpt function](https://github.com/lumeland/theme-simple-blog/blob/main/plugins.ts#L69-L71).
What do you mean?

**Comment by haturatu** [comment]
Wow, amazing!
I found it here as well, but I couldn’t figure out how to add it: [link](https://github.com/lumeland/theme-simple-blog/blob/4e76d8ea4a04cfaf0e67db12d8c0b2987642778e/src/posts/firstpost.md?plain=1#L21C12-L22C1)

Since I migrated articles from WordPress, thanks to you, I was able to dynamically include it.
`plugins.ts`
```
      .preprocess([".md"], (pages) => {
         for (const page of pages) {
           page.data.excerpt ??= (page.data.content as string)
             .split(/<!--\s*more\s*-->/i)[0]
             .slice(0, 100); 
         }
```

You're right, in the request I sent, the `<!-- more -->` sections would be ignored if migrating from other SSGs. 

It seems better to solve this in `plugins.ts` without editing the `src` as much as possible. Thanks!

**Comment by oscarotero** [comment]
Regarding the comments styles, this is the expected behavior, to optimize the space in narrow screens (removing the lateral margins).

In your case, you have customized the design by adding wrapper around the page content. So I think the change of `.comments` should belong to your custom styles. (It's completely fine to add custom styles with the property `extraHead` in your `_data.yml` file).

**Comment by haturatu** [comment]
It was the expected behavior. You're absolutely right.

I'll close this.
Thanks for your time. have a great day!

**Pull request closed without merging**
